//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MABEntities : DbContext
    {
        public MABEntities()
            : base("name=MABEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Telefonos> Telefonos { get; set; }
        public virtual DbSet<Lavarropas> Lavarropas { get; set; }
        public virtual DbSet<Reparaciones> Reparaciones { get; set; }
        public virtual DbSet<Repuestos> Repuestos { get; set; }
        public virtual DbSet<Entregas> Entregas { get; set; }
        public virtual DbSet<ReparacionesRepuestos> ReparacionesRepuestos { get; set; }
    
        public virtual ObjectResult<string> Procedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Procedure");
        }
    
        public virtual ObjectResult<string> MarcaMasReparado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MarcaMasReparado");
        }
    
        public virtual ObjectResult<string> ModeloMasReparado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ModeloMasReparado");
        }
    }
}
