//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReparacionesRepuestos
    {
        public int ReparacionesId { get; set; }
        public int RepuestosId { get; set; }
        public bool estado { get; set; }
    
        public virtual Reparaciones Reparaciones { get; set; }
        public virtual Repuestos Repuestos { get; set; }
    }
}
